#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2024.3.1.0"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    "commands2",
    "navx",
    "pathplannerlib",
    "phoenix6"
]

# Other pip packages to install
requires = [
    "frc6343",
    "robotpy-opencv; platform_machine == 'roborio'",
    "opencv-python; platform_machine != 'roborio'"
]
